SELECT CART_ID, IF(c.MINIMUN_REQUIREDMENT > SUM(SELECT PRICE FROM CART_PRODUCTS WHERE), 1, 0) AS 'ABUSED' 
FROM CART_PRODUCTS AS p 
INNER JOIN COUPONS AS c 
    ON p.CART_ID = c.CART_ID


SELECT manufacturer, sum(price)
FROM product_data
GROUP BY manufacturer
ORDER BY sum(price) DESC
;